"""
Creates data/pistols.db and populates it with all pistol data.
Run from the project root: python scripts/init_db.py
Re-running is safe — drops and recreates all tables.
"""
import sqlite3, pathlib, os

DB = pathlib.Path(__file__).parent.parent / "data" / "pistols.db"
SCHEMA = pathlib.Path(__file__).parent / "schema.sql"

PISTOLS = [
    # ── Spreadsheet data ──────────────────────────────────────────────────────
    dict(rank=1,    rd="1",     src="list", model="Glock 19",                               cal="9mm",   purpose="Do-All / Concealed / Home Defense",       price_min=499,  price_max=549,  pre_ban=False, rec="Covered by your existing Glock 17 stockpile. G17 factory mags are cross-compatible with G19.",                                                                                                  mag_price="$25–45/mag OEM; $20–30 Magpul PMAG GL9",               brands="Glock (OEM), Magpul PMAG GL9, ETS, KCI",                                     compat="G17, G19, G19X, G26 (flush with sleeve), G34, G45, G47; Kel-Tec Sub2000 Gen3, Ruger PC Carbine 9mm, CMMG Banshee 9mm, Just Right Carbines, FM-9 PCC",                                      note="Most widely compatible 9mm magazine in existence. 33rd OEM drum is fully reliable.",                                                                                                                     buy_pistols=["Glock 19"],                                                             buy_mags=["Glock 9mm 15rd","Glock 9mm 17rd","Glock 9mm 19rd extended","Glock 9mm 24rd","Glock 9mm 33rd"],                         mags=["15rd (factory)","17rd (G17 OEM)","19rd (extended)","24rd (OEM)","33rd (OEM drum)"]),
    dict(rank=2,    rd="2",     src="list", model="Glock 17 / Glock 47",                    cal="9mm",   purpose="Home Defense / Duty / Range",             price_min=499,  price_max=649,  pre_ban=False, rec="Already covered by your Glock 17 Gen6 stockpile. Same mags as your current pistol.",                                                                                                          mag_price="$25–45/mag OEM; $20–30 Magpul PMAG GL9",               brands="Glock (OEM), Magpul PMAG GL9, ETS, KCI, Lancer",                              compat="G17, G19, G19X, G26, G34, G45, G47, Polymer80 frames; Kel-Tec Sub2000 Gen3, Ruger PC Carbine 9mm, CMMG Banshee, Just Right Carbines, Angstadt Arms UDP-9",                                  note="The most cross-compatible 9mm magazine platform. Your Glock 17 stockpile works across all these.",                                                                                                       buy_pistols=["Glock 17","Glock 47"],                                                  buy_mags=["Glock 9mm 17rd","Glock 9mm 19rd","Glock 9mm 24rd","Glock 9mm 33rd"],                                                          mags=["17rd (factory)","19rd (extended)","24rd (OEM)","33rd (OEM drum)"]),
    dict(rank=3,    rd="3",     src="list", model="Sig Sauer P320 Series",                  cal="9mm",   purpose="Home Defense / Duty / Modular",           price_min=499,  price_max=749,  pre_ban=True,  rec="Buy 21-rd factory mags. They drop into any P320 full/carry/X-series frame. The 30rd is available for specific X-series setups.",                                                             mag_price="$40–55/mag OEM (21rd); $30–45 Mec-Gar (17rd)",         brands="Sig Sauer (OEM), Mec-Gar, Act-Mag",                                           compat="P320 Full, Compact, Carry, XFULL, XFIVE Legion, M17, M18, custom aftermarket grip modules; partially compatible with MCX Rattler (verify model)",                                            note="Modular polymer frame — swapping grip modules changes which mag size fits. 21rd is the sweet spot for capacity vs. flush carry.",                                                                        buy_pistols=["Sig P320 Full","Sig P320 Compact","Sig P320 X-Series","Sig M17","Sig M18"],buy_mags=["Sig P320 9mm 15rd","Sig P320 9mm 17rd","Sig P320 9mm 21rd","Sig P320 9mm 30rd"],                                             mags=["15rd (Compact)","17rd (Full)","21rd (XFULL / XFIVE)","30rd (extended)"]),
    dict(rank=4,    rd="4",     src="list", model="Sig Sauer P365 / P365X / P365-Xmacro",  cal="9mm",   purpose="Concealed / EDC",                         price_min=449,  price_max=679,  pre_ban=True,  rec="Buy 17-rd Xmacro mags now. Standard P365/P365X max out at 12rd — Xmacro frame required for 17rd.",                                                                                           mag_price="~$50–65/mag OEM (17rd Xmacro)",                         brands="Sig Sauer (OEM only — proprietary)",                                          compat="P365, P365X, P365XL, P365-Xmacro. Note: 17rd mag requires Xmacro or compatible grip module — won't fit standard P365 frame.",                                                                note="Modular basepads allow capacity extension. Only the Xmacro grip module accepts the 17rd magazine.",                                                                                                       buy_pistols=["Sig P365","Sig P365X","Sig P365XL","Sig P365 Xmacro"],                  buy_mags=["Sig P365 9mm 12rd","Sig P365XL 9mm 15rd","Sig P365 Xmacro 9mm 17rd"],                                                         mags=["12rd (P365/P365X)","15rd (P365XL)","17rd (Xmacro only)"]),
    dict(rank=5,    rd="5",     src="list", model="S&W M&P9 M2.0 Full-Size",                cal="9mm",   purpose="Home Defense / Duty / Open Carry",        price_min=499,  price_max=599,  pre_ban=True,  rec="Buy 17-rd OEM or Mec-Gar mags, and a few 23-rd PC extended for HD use. ~$30–45/mag.",                                                                                                        mag_price="$30–40/mag OEM (17rd); $40–55 OEM (23rd)",             brands="Smith & Wesson (OEM), Mec-Gar (17rd flush compatible)",                        compat="M&P9 Full, M&P9 M2.0 Compact (with mag sleeve), M&P9 CORE; S&W FPC folding carbine, S&W Response PCC. NOTE: M&P Shield Plus uses a DIFFERENT proprietary 1.5-stack mag — NOT compatible.",  note="Most reliable 17rd mag for M&P9 is Mec-Gar — slightly better fit than OEM for some users.",                                                                                                              buy_pistols=["S&W M&P9 M2.0"],                                                        buy_mags=["Smith Wesson MP9 M2.0 17rd","Smith Wesson MP9 M2.0 23rd"],                                                                    mags=["17rd (Full-Size standard)","23rd (PC extended)"]),
    dict(rank=6,    rd="6",     src="rec",  model="1911 Government / Commander (.45 ACP)",  cal=".45",   purpose="Home Defense / Heritage / Competition",   price_min=499,  price_max=1499, pre_ban=False, rec="Standard 1911 maxes at 10rd — not affected by the ban. No pre-ban action needed. Focus on buying quality mags (Wilson Combat, Chip McCormick) for reliability.",                            mag_price="$15–25/mag GI surplus; $20–35 Wilson Combat / Chip McCormick (8rd); $25–40 extended (10rd)", brands="Colt (OEM), Wilson Combat, Chip McCormick, Metalform, Tripp Research, Kimber, Ed Brown, Nighthawk", compat="All standard GI-spec single-stack 1911 mags are cross-compatible across: Colt Government/Commander/Officer, Springfield Mil-Spec/Range Officer/Loaded, Kimber Custom/Pro/Ultra, Rock Island Armory GI/Tactical/M1911-A1, Ruger SR1911, Dan Wesson, Remington R1, Sig 1911, Auto-Ordnance. NOTE: Officers (3\") uses shorter 6rd mags; verify length before buying.", note="Classic John Browning design (1911). Single-stack .45 ACP — factory max 8rd (modern) or 7rd (GI). Wilson Combat 8rd mags are considered the gold standard for reliability. Double-stack 2011 variants (Staccato, Prodigy) are listed separately as rank #14.", buy_pistols=["1911 Government 45 ACP","1911 Commander 45 ACP"],    buy_mags=["1911 45acp 7rd","1911 45acp 8rd","1911 45acp 10rd extended"],                                                                 mags=["7rd (GI standard)","8rd (modern standard)","10rd (flush extended)"]),
    dict(rank=7,    rd="7",     src="rec",  model="HK VP9 / VP9SK",                         cal="9mm",   purpose="Home Defense / Duty / Competition",       price_min=649,  price_max=749,  pre_ban=True,  rec="Buy 17-rd and 20-rd HK OEM mags. Outstanding factory trigger. VP9 and P30 share identical mags — stock one supply for both. ~$35–55/mag.",                                                 mag_price="$35–45/mag OEM (17rd); $50–60 OEM (20rd)",             brands="HK (OEM), Mec-Gar (VP9/P30 compatible)",                                      compat="VP9, VP9SK (full-size + sleeve), HK P30, HK P30L, HK P30SK (full-size + sleeve). P30 and VP9 use identical magazines — fully interchangeable.",                                              note="Paddle mag release is polarizing — most shooters adapt quickly and prefer it. 20-rd extended available and very reliable.",                                                                               buy_pistols=["HK VP9","HK VP9SK"],                                                    buy_mags=["HK VP9 9mm 17rd","HK VP9 9mm 20rd extended"],                                                                                 mags=["17rd (standard paddle-release)","20rd (extended)"]),
    dict(rank=8,    rd="8",     src="list", model="Springfield Hellcat / Hellcat Pro",       cal="9mm",   purpose="Concealed (EDC)",                         price_min=499,  price_max=599,  pre_ban=True,  rec="Buy 17-rd Hellcat Pro mags. Only the Hellcat Pro frame physically accepts the 17rd mag.",                                                                                                    mag_price="$35–50/mag OEM (17rd)",                                 brands="Springfield Armory (OEM — proprietary design)",                               compat="All Hellcat variants (standard mags), Hellcat Pro frame required for 17rd. No cross-compat with other platforms.",                                                                             note="Proprietary magazine design. 17rd extends slightly past the grip on Pro models. Flush-fit on original Hellcat is 11rd only.",                                                                           buy_pistols=["Springfield Hellcat","Springfield Hellcat Pro"],                         buy_mags=["Springfield Hellcat 9mm 11rd","Springfield Hellcat 9mm 13rd","Springfield Hellcat Pro 9mm 17rd"],                              mags=["11rd (Hellcat standard flush)","13rd (Hellcat flush-extended)","17rd (Hellcat Pro only)"],  link_mag="https://gunmagwarehouse.com/springfield-armory-hellcat-pro-9mm-17-round-magazine.html"),
    dict(rank=9,    rd="9",     src="list", model="Walther PDP Full-Size",                   cal="9mm",   purpose="Home Defense / Duty / Competition",       price_min=549,  price_max=699,  pre_ban=True,  rec="Buy 18-rd or 20-rd Full-Size mags. ~$45–60/mag OEM. Full-Size mags fit Compact with sleeve.",                                                                                               mag_price="$45–55/mag OEM (18rd); $50–65 OEM (20rd)",             brands="Walther (OEM), Mec-Gar (PDP-compatible variants)",                             compat="PDP Full-Size 4\", PDP Full-Size 5\", PDP Compact (with full-size sleeve), PDP-F Sub-Compact; PDP Match Slim (different mag).",                                                               note="⚠️ CRITICAL: Walther PDP has NO internal mechanical mag stop. Over-seating the magazine damages the polymer frame. Seat firmly but do not slam. Known issue — verify before purchase.",              buy_pistols=["Walther PDP Full-Size","Walther PDP Compact"],                           buy_mags=["Walther PDP 9mm 15rd compact","Walther PDP 9mm 18rd full size","Walther PDP 9mm 20rd extended"],                              mags=["15rd (PDP Compact)","18rd (PDP Full-Size 4\")","20rd (PDP Full-Size extended)"]),
    dict(rank=10,   rd="10",    src="list", model="S&W M&P Shield Plus",                    cal="9mm",   purpose="Concealed (EDC)",                         price_min=449,  price_max=499,  pre_ban=False, rec="Maxes out at 13rd — not affected by the ban. No pre-ban action needed.",                                                                                                                    mag_price="$30–40/mag OEM",                                        brands="Smith & Wesson (OEM — proprietary 1.5-stack design)",                         compat="M&P Shield Plus 9mm only. NOT compatible with full-size M&P9 magazines despite similar appearance.",                                                                                          note="Proprietary 1.5-column stack mag — unique to this pistol. Do not confuse with full-size M&P9 mags.",                                                                                                     buy_pistols=["S&W M&P Shield Plus"],                                                  buy_mags=["Smith Wesson Shield Plus 9mm 10rd","Smith Wesson Shield Plus 9mm 13rd"],                                                      mags=["10rd (flush)","13rd (extended)"]),
    dict(rank=11,   rd="11",    src="list", model="Canik METE / SFx Rival",                 cal="9mm",   purpose="Competition / Home Defense",              price_min=399,  price_max=649,  pre_ban=True,  rec="Buy 20-rd OEM extended mags. Best value performance pistol — ~$35–45/mag OEM.",                                                                                                             mag_price="$35–45/mag OEM (20rd)",                                 brands="Canik (OEM), Mec-Gar (select models)",                                        compat="METE SFT, METE SFX, SFx Rival, SFx Rival-S, TP9SFx, TP9SF Elite, TP9DA/DP, Canik FANATIK. NOTE: Canik MC9 micro uses DIFFERENT, shorter mags — not compatible with full-size METE line.", note="MC9 mags ≠ METE mags. If buying both Canik pistols, buy mags separately. Exceptional value competition trigger.",                                                                                       buy_pistols=["Canik METE SFT","Canik SFx Rival"],                                     buy_mags=["Canik METE 9mm 18rd","Canik METE 9mm 20rd extended"],                                                                         mags=["18rd (METE SFT standard)","20rd (extended)"]),
    dict(rank=12,   rd="12",    src="list", model="Glock 43X / 48 (Slimline)",              cal="9mm",   purpose="Concealed (EDC Slimline)",                price_min=449,  price_max=519,  pre_ban=False, rec="Shield Arms S15 provides 15rd in the same physical footprint as the factory 10rd — right at the ban limit. No pre-ban buying needed.",                                                       mag_price="$15–22/mag OEM; $35–45 Shield Arms S15",               brands="Glock (OEM), Shield Arms (S15 steel aftermarket)",                             compat="G43X and G48 only — single-stack slim frame. No cross-compatibility with full-size Glock 9mm mags.",                                                                                          note="Shield Arms S15 requires replacing the factory plastic mag release with a Shield Arms steel mag release (included in kit). S15 is at the 15rd limit — not affected by ban.",                            buy_pistols=["Glock 43X","Glock 48"],                                                 buy_mags=["Glock 43X 9mm 10rd OEM","Shield Arms S15 Glock 43X 15rd"],                                                                   mags=["10rd (OEM flush)","15rd (Shield Arms S15 steel)"]),
    dict(rank=13,   rd="13",    src="rec",  model="CZ Shadow 2 / CZ 75 SP-01",              cal="9mm",   purpose="Competition / DA-SA Target",              price_min=699,  price_max=1349, pre_ban=True,  rec="Buy Mec-Gar 19-rd flush mags — they are the same physical size as the OEM 17-rd. Best DA/SA competition trigger available. ~$25–35/mag Mec-Gar.",                                         mag_price="$35–45/mag CZ OEM (17rd); $25–35 Mec-Gar (19rd flush)", brands="CZ-USA (OEM), Mec-Gar, Arredondo, ETS, Henning",                              compat="CZ Shadow 2, Shadow 2 OR, Shadow 2 Compact, CZ 75 SP-01 Shadow, CZ 75 B, CZ 75 D PCR, CZ 75 BD, CZ P-07, CZ P-09; Arex Rex Zero 1 / Delta Gen 2 (CZ 75 magazine pattern).", note="The entire CZ 75 platform (~50+ pistol models across 50+ years) shares the same double-stack 9mm magazine. Largest single-platform mag ecosystem in the world. Mec-Gar 19rd is flush to 17rd OEM.", buy_pistols=["CZ Shadow 2","CZ 75 SP-01"],                                            buy_mags=["CZ Shadow 2 9mm 17rd","Mec-Gar CZ 75 9mm 19rd"],                                                                              mags=["17rd (CZ OEM)","19rd (Mec-Gar flush-fit — same size as 17rd)"]),
    dict(rank=14,   rd="14",    src="list", model="Springfield Prodigy / Staccato 2011",    cal="9mm",   purpose="Competition / Premium Duty",              price_min=1299, price_max=2799, pre_ban=True,  rec="Buy 20-rd and 26-rd mags. MBX 31-rd is the highest-capacity factory-fit mag. ~$50–80/mag.",                                                                                                mag_price="$50–65/mag OEM (20rd); $65–80 MBX/Check-Mate (26–31rd)", brands="Staccato (OEM), Springfield (OEM), Check-Mate Industries, MBX, Dawson Precision, Henning", compat="All 2011 double-stack pattern: Staccato C/C2/P/XC, Springfield Prodigy, Apollo 11, Oracle Arms, SPS Platense, Atlas Gunworks, DVC, Limcat, Infinity, STI (legacy).", note="Standard 2011 double-stack magazine pattern — widely shared across all premium 2011-platform pistols. MBX 31-rd is the legal max before ban.",                                                            buy_pistols=["Springfield Prodigy","Staccato P","Staccato C2","Staccato XC"],          buy_mags=["Staccato 2011 9mm 17rd","Staccato 2011 9mm 20rd","2011 9mm 26rd extended","MBX 2011 9mm 31rd"],                               mags=["17rd (standard 2011)","20rd (extended)","26rd (extended+)","31rd (MBX max)"]),
    dict(rank=15,   rd="15",    src="list", model="Ruger LCP Max (.380 ACP)",               cal=".380",  purpose="Pocket Carry / Deep Concealment",         price_min=369,  price_max=429,  pre_ban=False, rec=".380 ACP — maxes out at 12rd. Not affected by ban.",                                                                                                                                       mag_price="$25–35/mag OEM",                                        brands="Ruger (OEM — proprietary)",                                                   compat="LCP Max only. Not compatible with original LCP, LCP II, or LCP Custom.",                                                                                                                      note="Deep concealment .380. No high-cap options exist or are planned. Maxes at 12rd factory.",                                                                                                                buy_pistols=["Ruger LCP Max"],                                                        buy_mags=["Ruger LCP Max 380acp 10rd","Ruger LCP Max 380acp 12rd"],                                                                      mags=["10rd (flush)","12rd (extended)"]),
    dict(rank=16,   rd="16",    src="list", model="FN 509 Series",                          cal="9mm",   purpose="Tactical / Home Defense / Duty",          price_min=549,  price_max=999,  pre_ban=True,  rec="Buy 17-rd and 24-rd FN OEM mags. The 24-rd is flush-profiled for concealed carry on the Tactical. ~$40–60/mag.",                                                                           mag_price="$40–50/mag OEM (17rd); $50–65 OEM (24rd)",             brands="FN America (OEM only — proprietary design)",                                  compat="FN 509 LS Edge, FN 509 Full-Size, FN 509 Midsize, FN 509 Compact MRD, FN 509 Tactical. NOTE: FN 509 .22 LR conversion uses completely different mags.",                                     note="Fully proprietary FN magazine — limited aftermarket. The 24-rd extended is reportedly flush-profile on the Tactical model. Buy OEM only.",                                                               buy_pistols=["FN 509 Full-Size","FN 509 Midsize","FN 509 Tactical","FN 509 LS Edge"],  buy_mags=["FN 509 9mm 17rd","FN 509 9mm 24rd extended"],                                                                                 mags=["17rd (standard — all models)","24rd (FN 509 Tactical extended)"]),
    dict(rank=17,   rd="17",    src="list", model="CZ P-10 Series",                         cal="9mm",   purpose="Home Defense / Concealed",                price_min=349,  price_max=459,  pre_ban=True,  rec="Buy 19-rd P-10F mags. They work in P-10C with the included grip sleeve. ~$35–50/mag OEM.",                                                                                                  mag_price="$35–45/mag OEM (17rd); $40–50 OEM (19rd)",             brands="CZ-USA (OEM), Mec-Gar (limited)",                                              compat="P-10F (19rd native), P-10C (P-10F mags with sleeve), P-10S (P-10C mags with sleeve); CZ P-07 and P-09 are hammer-fired variants sharing similar but not identical mag body.", note="P-10F mags fit P-10C only with the factory grip sleeve — not a direct drop-in without it. P-07/P-09 share similar pattern but verify before depending on it.",                                             buy_pistols=["CZ P-10F","CZ P-10C","CZ P-10S"],                                       buy_mags=["CZ P-10C 9mm 15rd","CZ P-10F 9mm 17rd","CZ P-10F 9mm 19rd"],                                                                 mags=["15rd (P-10C standard)","17rd (P-10F / P-10C extended)","19rd (P-10F factory max)"]),
    dict(rank=18,   rd="18",    src="list", model="Taurus TX22 (.22 LR)",                   cal=".22",   purpose="Plinking / Training / Rimfire",           price_min=289,  price_max=449,  pre_ban=True,  rec="Buy 22-rd mags for Competition/T.O.R.O. and 16-rd for standard TX22. Cheap rimfire mags worth stocking in bulk.",                                                                         mag_price="$25–35/mag OEM (16rd); $30–40 OEM (22rd)",             brands="Taurus (OEM only — proprietary .22 LR)",                                      compat="TX22 Standard, TX22 Gen 2, TX22 T.O.R.O., TX22 Competition SCR. No cross-compatibility with other platforms.",                                                                               note="Best budget rimfire pistol for practice. Stocking 22rd mags for sub-$35 each is low cost for high-volume training.",                                                                                      buy_pistols=["Taurus TX22","Taurus TX22 Competition"],                                buy_mags=["Taurus TX22 22lr 16rd","Taurus TX22 22lr 22rd"],                                                                              mags=["16rd (.22 LR)","22rd (.22 LR)"]),
    dict(rank=19,   rd="19",    src="rec",  model="Beretta 92X / M9A4",                     cal="9mm",   purpose="Home Defense / Competition / Legacy",     price_min=749,  price_max=1149, pre_ban=True,  rec="Buy Mec-Gar 18-rd flush mags — same physical size as the OEM 15-rd, 3 extra rounds free. Mec-Gar 18rd is the best mag upgrade in 9mm. ~$25–35/mag Mec-Gar.",                              mag_price="$35–45/mag OEM (17rd); $25–35 Mec-Gar (18rd flush); $30–40 Mec-Gar (20rd extended)", brands="Beretta (OEM), Mec-Gar, Wilson Combat, Chip McCormick, Langdon Tactical", compat="92FS, 92X, 92X Performance, 92X RDO, M9, M9A1, M9A4, 92A1; Beretta CX4 Storm carbine (same 9mm mags!); Beretta ARX100 (some compatibility).", note="Mec-Gar 18-rd flush is arguably the best-value magazine upgrade in all of 9mm. CX4 Storm carbine uses exact same mags — exceptional PCC/pistol sharing ecosystem.", buy_pistols=["Beretta 92X Performance","Beretta M9A4","Beretta 92FS"],                 buy_mags=["Beretta 92 9mm 15rd OEM","Beretta 92 9mm 17rd OEM","Mec-Gar Beretta 92 9mm 18rd","Mec-Gar Beretta 92 9mm 20rd"],              mags=["15rd (OEM standard 92FS)","17rd (factory 92X full)","18rd (Mec-Gar flush-fit)","20rd (Mec-Gar extended)"]),
    dict(rank=20,   rd="20",    src="rec",  model="Springfield XD-M Elite",                 cal="9mm",   purpose="Home Defense / Competition",              price_min=549,  price_max=699,  pre_ban=True,  rec="Buy 22-rd mags for the 5.25\" OSP / Precision — highest single-stack factory capacity in the price range. ~$40–50/mag OEM.",                                                              mag_price="$40–50/mag OEM (19rd); $45–55 OEM (22rd)",             brands="Springfield Armory (OEM), SGM Tactical",                                      compat="XD-M Elite 3.8\", XD-M Elite 4.5\", XD-M Elite 5.25\" Precision; XD-M Compact (with sleeve).",                                                                                              note="⚠️ NOT backward-compatible with original XD or original XD-M mags. Elite is a completely redesigned proprietary magazine. Do not mix with older XD-M stock.",                                          buy_pistols=["Springfield XDM Elite 4.5","Springfield XDM Elite 5.25 OSP"],           buy_mags=["Springfield XDM Elite 9mm 19rd","Springfield XDM Elite 9mm 22rd"],                                                            mags=["19rd (3.8\" / 4.5\" models)","22rd (5.25\" Precision / OSP)"]),
    dict(rank=21,   rd="21",    src="list", model="Taurus G3 / G3C",                        cal="9mm",   purpose="Budget Carry / Home Defense",             price_min=249,  price_max=319,  pre_ban=True,  rec="Buy 17-rd full-size G3 mags. Very affordable at ~$25–35/mag. Best budget 9mm stockpile option.",                                                                                           mag_price="$25–35/mag OEM (17rd); $30–40 Mec-Gar",               brands="Taurus (OEM), Mec-Gar, SGM Tactical",                                         compat="G3, G3C, G3X, G3XL; partial compatibility reported with older Taurus PT92/PT100 variants — verify before relying on it.",                                                                     note="Best price-per-round-capacity value on the list. At $250 for the gun and $30/mag for 17rd mags, this is the cheapest pre-ban setup available.",                                                          buy_pistols=["Taurus G3","Taurus G3C","Taurus G3X"],                                  buy_mags=["Taurus G3 9mm 10rd","Taurus G3 9mm 15rd","Taurus G3 9mm 17rd"],                                                              mags=["10rd (G3C flush)","15rd (G3C extended / G3 standard)","17rd (G3 full-size extended)"]),
    dict(rank=22,   rd="22",    src="list", model="Springfield Echelon",                    cal="9mm",   purpose="Home Defense / Duty / Tactical",          price_min=589,  price_max=649,  pre_ban=True,  rec="Buy 20-rd OEM mags. Proprietary — no aftermarket options. ~$45–55/mag.",                                                                                                                    mag_price="$45–55/mag OEM (20rd)",                                 brands="Springfield Armory (OEM only — proprietary design)",                          compat="Echelon Standard, Echelon Comp. No cross-compatibility with any other platform.",                                                                                                              note="Fully proprietary magazine — buy OEM only. Modular optics plate accepts most major red dots. Grip fits medium-large hands well.",                                                                         buy_pistols=["Springfield Echelon"],                                                  buy_mags=["Springfield Echelon 9mm 17rd","Springfield Echelon 9mm 20rd"],                                                                mags=["17rd (standard)","20rd (extended)"]),
    dict(rank=23,   rd="23",    src="rec",  model="IWI Masada / Masada ACE",                cal="9mm",   purpose="Home Defense / Duty",                     price_min=449,  price_max=549,  pre_ban=True,  rec="Buy 17-rd and 21-rd IWI OEM mags. Israeli mil-spec build at civilian price. Aftermarket is growing but limited — buy OEM now. ~$35–55/mag.",                                             mag_price="$35–45/mag OEM (17rd); $45–55 OEM (21rd)",             brands="IWI (OEM — proprietary, limited aftermarket)",                                compat="Masada Standard, Masada ACE (optics-ready). Masada Slim uses a different shorter magazine.",                                                                                                  note="Designed and built by Israel Weapon Industries — same company behind the Tavor. Polymer frame with steel chassis insert. Proprietary mag — buy OEM while available.",                                     buy_pistols=["IWI Masada","IWI Masada ACE"],                                          buy_mags=["IWI Masada 9mm 17rd","IWI Masada 9mm 21rd"],                                                                                  mags=["17rd (standard)","21rd (extended)"]),
    dict(rank=24,   rd="24",    src="list", model="Ruger Mark IV (.22 LR)",                 cal=".22",   purpose="Target / Rimfire Competition",            price_min=449,  price_max=699,  pre_ban=False, rec="Factory maxes at 10rd — not affected by the ban. ProMag makes a 25rd aftermarket but it's unreliable.",                                                                                     mag_price="$20–30/mag OEM (10rd)",                                 brands="Ruger (OEM), ProMag (25rd — low reliability, not recommended)",               compat="Mark IV standard, Mark IV Target, Mark IV 22/45, Mark IV 22/45 Lite. All Mark IV share the same single-stack .22 LR mag.",                                                                   note="Iconic .22 LR target pistol. Factory 10rd mag is reliable; aftermarket 25rd ProMag is generally avoided by serious shooters.",                                                                            buy_pistols=["Ruger Mark IV","Ruger Mark IV 22/45","Ruger Mark IV Target"],            buy_mags=["Ruger Mark IV 22lr 10rd"],                                                                                                     mags=["10rd (OEM standard)"]),
    dict(rank=25,   rd="25",    src="rec",  model="Beretta APX A2 Full-Size",               cal="9mm",   purpose="Home Defense / Duty",                     price_min=399,  price_max=499,  pre_ban=True,  rec="Buy 17-rd APX A2 Full-Size OEM mags. Best ergonomics in the budget duty-pistol segment. ~$40–50/mag.",                                                                                     mag_price="$40–50/mag OEM (17rd)",                                 brands="Beretta (OEM — APX-specific proprietary design)",                             compat="APX A2 Full-Size, APX A2 Carry (different smaller mag). NOT compatible with Beretta 92-series mags despite sharing the brand.",                                                               note="APX A2 mags are proprietary — completely different from the 92FS. Major improvement over original APX. Aggressive texturing and excellent trigger reset.",                                               buy_pistols=["Beretta APX A2 Full-Size","Beretta APX A2 Carry"],                       buy_mags=["Beretta APX A2 9mm 15rd compact","Beretta APX A2 9mm 17rd full size"],                                                        mags=["15rd (Compact)","17rd (Full-Size standard)"]),
    dict(rank=26,   rd="26",    src="rec",  model="S&W SD9 / SD9VE",                        cal="9mm",   purpose="Budget Home Defense",                     price_min=299,  price_max=379,  pre_ban=True,  rec="Buy 16-rd OEM mags — it's 1 round over the limit and will be banned for sale. One of the cheapest pre-ban guns on the market. ~$30–40/mag OEM.",                                         mag_price="$30–40/mag OEM (16rd)",                                 brands="Smith & Wesson (OEM — proprietary SD-series design)",                         compat="SD9, SD9VE, SD9VE 2.0. NOT compatible with M&P9 or Shield Plus mags despite same brand.",                                                                                                    note="Ultra-budget option. 16rd is exactly 1 round over the limit — worth stocking for the price. Long trigger pull by design but reliable and very affordable.",                                             buy_pistols=["S&W SD9VE"],                                                            buy_mags=["Smith Wesson SD9VE 9mm 16rd"],                                                                                                mags=["16rd (Full-Size standard)"]),
    dict(rank=27,   rd="27",    src="list", model="S&W Bodyguard 2.0 (.380 ACP)",           cal=".380",  purpose="Pocket Carry / Backup Gun",               price_min=389,  price_max=449,  pre_ban=False, rec=".380 ACP — maxes at 12rd. Not affected by ban.",                                                                                                                                           mag_price="$25–35/mag OEM",                                        brands="Smith & Wesson (OEM — proprietary)",                                          compat="Bodyguard 2.0 only. Not compatible with original Bodyguard 380.",                                                                                                                             note="Redesigned from the ground up vs. original Bodyguard. Improved trigger and ergonomics. Still limited to 12rd max.",                                                                                       buy_pistols=["S&W Bodyguard 2.0"],                                                    buy_mags=["Smith Wesson Bodyguard 2.0 380 10rd","Smith Wesson Bodyguard 2.0 380 12rd"],                                                  mags=["10rd (flush)","12rd (extended)"]),
    dict(rank=28,   rd="28",    src="rec",  model="Arex Rex Zero 1 / Delta Gen 2",          cal="9mm",   purpose="Home Defense / Competition",              price_min=499,  price_max=649,  pre_ban=True,  rec="Buy Mec-Gar 19-rd CZ 75-pattern mags — same mags as CZ Shadow 2 / CZ 75. Full CZ 75 ecosystem compatibility. ~$25–35/mag Mec-Gar.",                                                     mag_price="$30–40/mag Arex OEM; $25–35 Mec-Gar CZ 75 pattern (19rd)", brands="Arex (OEM), Mec-Gar (CZ 75 pattern), CZ-USA (OEM)",                          compat="Rex Zero 1S, Zero 1TC, Zero 1CP, Zero 1 Standard, Delta Gen 2; ENTIRE CZ 75 magazine ecosystem — CZ Shadow 2, CZ 75 B, CZ 75 SP-01, CZ P-07, CZ P-09, etc.",                                note="Slovenian CZ 75 clone with military contract pedigree. Uses standard CZ 75 double-stack mag — buy Mec-Gar CZ 75 19rd mags and they work in both Rex and any CZ 75 platform.",                          buy_pistols=["Arex Rex Zero 1","Arex Delta Gen 2"],                                    buy_mags=["Arex Rex Zero 1 9mm 17rd","Mec-Gar CZ 75 9mm 19rd"],                                                                          mags=["17rd (CZ 75 pattern — OEM)","19rd (Mec-Gar CZ 75 flush-fit)"]),
    dict(rank=29,   rd="29",    src="rec",  model="Kel-Tec PMR-30 (.22 WMR)",               cal=".22",   purpose="Plinking / Unique / Rimfire",             price_min=399,  price_max=469,  pre_ban=True,  rec="Buy extra 30-rd .22 WMR mags now — the 30-rd is STANDARD capacity and will be banned for sale. Same mag works in the Kel-Tec CMR-30 carbine. ~$35–45/mag OEM.",                          mag_price="$35–45/mag OEM (30rd .22 WMR)",                         brands="Kel-Tec (OEM only — proprietary .22 WMR)",                                    compat="PMR-30 pistol; Kel-Tec CMR-30 carbine (same 30rd .22 WMR magazine — perfect PCC pair).",                                                                                                     note="Only pistol on this list where 30 rounds is the standard factory capacity. .22 WMR (not .22 LR) — higher velocity rimfire. Pairs perfectly with CMR-30 carbine using same mags. Unique stockpile value.", buy_pistols=["Kel-Tec PMR-30"],                                                       buy_mags=["Kel-Tec PMR-30 22wmr 30rd"],                                                                                                  mags=["30rd (.22 WMR — standard factory capacity)"]),
    # ── Wilderness / Bear Defense — 10mm ──────────────────────────────────────
    dict(rank=30,   rd="30",    src="rec",  model="Glock 20 / Glock 40 MOS (10mm Auto)",   cal="10mm",  purpose="Wilderness / Home Defense / Hunting",     price_min=549,  price_max=699,  pre_ban=True,  rec="Buy 17-rd KCI extended mags before ban. The G20 is the #1 recommended semi-auto for bear defense. CRITICAL: Use hard cast flat-nose loads (Buffalo Bore, Underwood, DoubleTap) — hollow points won't penetrate enough on large bears.", mag_price="$30–40/mag Glock OEM (15rd); $20–30 KCI (17rd extended)", brands="Glock (OEM), KCI, ETS",                                                       compat="G20 and G40 MOS share identical 15rd magazines. G29 (sub-compact) uses same mags with factory grip sleeve. NOT cross-compatible with 9mm Glock mags.",                                        note="⚠️ BEAR DEFENSE: Hard cast flat-nose bullets only. Buffalo Bore 220gr HC, Underwood 200gr HC, or DoubleTap 200gr HC recommended. G40 MOS adds a 6\" barrel for higher velocity and optic mounting. Best semi-auto option for bear country.", buy_pistols=["Glock 20 10mm","Glock 40 MOS 10mm"],                                    buy_mags=["Glock 20 10mm 15rd","KCI Glock 20 10mm 17rd extended"],                                                                       mags=["15rd (factory standard)","17rd (KCI / aftermarket extended)"]),
    dict(rank=31,   rd="31",    src="rec",  model="Glock 29 SF (10mm Auto — Compact)",      cal="10mm",  purpose="Wilderness Carry / Compact Defense",      price_min=499,  price_max=599,  pre_ban=False, rec="Most concealable 10mm available. Use G20 15rd mags with factory sleeve for full capacity. 15rd is at the ban limit — no pre-ban action needed for standard setup.",                         mag_price="$30–40/mag Glock G20 OEM (15rd, with sleeve)",          brands="Glock (OEM — G20 mags compatible with sleeve)",                               compat="G29 native 10rd. G20/G40 full-size 15rd mags fit with factory grip sleeve included with pistol.",                                                                                            note="Best choice when weight and concealability matter in the field. Same ballistics as G20 from the shorter barrel. The SF (Short Frame) variant fits smaller hands.",                                        buy_pistols=["Glock 29 10mm","Glock 29 SF 10mm"],                                     buy_mags=["Glock 29 10mm 10rd","Glock 20 10mm 15rd"],                                                                                    mags=["10rd (factory flush)","15rd (G20 OEM — fits with factory grip sleeve)"]),
    dict(rank=32,   rd="32",    src="rec",  model="EAA Witness / Tanfoglio Hunter (10mm Auto)", cal="10mm", purpose="Wilderness / Hunting / Competition",  price_min=499,  price_max=749,  pre_ban=False, rec="CZ 75-pattern double-stack 10mm with 15rd factory capacity — at the limit, no pre-ban action needed. Hunter model has 6\" barrel for maximum velocity. Very accurate at range.",            mag_price="$35–55/mag OEM",                                        brands="EAA / Tanfoglio (OEM — proprietary 10mm double-stack)",                       compat="EAA Witness Full-Size, Witness Hunter, Witness Elite, Witness Match; Tanfoglio Stock, Combat, Limited, Gold Custom (all 10mm variants share mag pattern).",                                   note="Italian-made on a CZ 75 chassis. The Hunter 10mm with a 6\" barrel is a purpose-built woods gun. Very reliable with hot 10mm loads. Limited US aftermarket support.",                                     buy_pistols=["EAA Witness 10mm","EAA Witness Hunter 10mm"],                            buy_mags=["EAA Witness 10mm 15rd"],                                                                                                       mags=["15rd (double-stack factory)"]),
    dict(rank=33,   rd="33",    src="rec",  model="1911 Platform — 10mm (Bruin / Camp Guard / Delta Elite)", cal="10mm", purpose="Wilderness / Heritage", price_min=899,  price_max=2499, pre_ban=False, rec="Single-stack 10mm in a 1911 chassis. 8-9rd is well under the ban limit — no pre-ban needed. The Dan Wesson Bruin is the purpose-built woods carry choice.",                             mag_price="$30–55/mag (1911 10mm OEM varies by brand); $30–40 Metalform/Wilson Combat", brands="Dan Wesson (OEM), Kimber (OEM), Colt (OEM), Wilson Combat, Metalform, Chip McCormick (10mm rated)", compat="Dan Wesson Bruin, Razorback, RZ-10 Commander; Kimber Camp Guard 10, Rapide 10mm; Colt Delta Elite; Rock Island 10mm; Ruger SR1911 10mm. All share GI-spec single-stack 10mm mag pattern.", note="Dan Wesson Bruin is stainless steel with a 4\" Commander barrel — specifically designed for wilderness carry. Colt Delta Elite is the classic that started the 10mm 1911 category. All use same mag pattern.", buy_pistols=["Dan Wesson Bruin 10mm","Kimber Camp Guard 10mm","Colt Delta Elite 10mm","Ruger SR1911 10mm"], buy_mags=["1911 10mm 8rd","1911 10mm 9rd extended"],                                                                                      mags=["8rd (standard single-stack)","9rd (some extended models)"]),
    dict(rank=34,   rd="34",    src="rec",  model="Sig Sauer P220 Legion (10mm Auto)",      cal="10mm",  purpose="Wilderness / Premium Duty",               price_min=1099, price_max=1299, pre_ban=False, rec="Premium DA/SA 10mm — 8rd is under the ban limit, no pre-ban needed. The finest factory DA/SA trigger available in 10mm. Excellent for shooters who prefer a hammer-fired action.",       mag_price="$45–60/mag Sig OEM (8rd)",                              brands="Sig Sauer (OEM — proprietary P220 10mm single-stack)",                        compat="P220 Legion 10mm only. P220 10mm mags are NOT cross-compatible with P220 .45 ACP mags despite same frame.",                                                                                  note="Sig's P220 in 10mm uses an alloy frame with a rail. Superb accuracy and the best double-action trigger pull available from the factory in 10mm. Limited capacity but exceptional quality.",               buy_pistols=["Sig P220 Legion 10mm"],                                                 buy_mags=["Sig P220 10mm 8rd"],                                                                                                          mags=["8rd (single-stack DA/SA)"]),
    dict(rank=35,   rd="35",    src="rec",  model="Beretta CX4 Storm (9mm PCC)",            cal="9mm",   purpose="Home Defense / Plinking / PCC",           price_min=799,  price_max=999,  pre_ban=True,  rec="Buy Mec-Gar 18-rd and 20-rd Beretta 92-pattern mags now — same mags as the Beretta 92X/M9A4 already on this list. One mag purchase covers both your pistol and this carbine.",           mag_price="$25–35/mag Mec-Gar (18rd flush); $30–40 Mec-Gar (20rd extended)", brands="Beretta (OEM), Mec-Gar, Wilson Combat",                                        compat="Shares mags with: Beretta 92FS, 92X, 92X Performance, M9, M9A1, M9A4 — buy one set of mags for both the pistol and this carbine.",                                                           note="Pistol-caliber carbine (PCC), not a handgun. Discontinued by Beretta — buy new old stock or used. The magazine-sharing ecosystem with the 92-series is its primary value proposition.",                   buy_pistols=["Beretta CX4 Storm 9mm"],                                                buy_mags=["Beretta 92 9mm 15rd OEM","Beretta 92 9mm 17rd OEM","Mec-Gar Beretta 92 9mm 18rd","Mec-Gar Beretta 92 9mm 20rd"],              mags=["15rd (Beretta 92 OEM)","17rd (Beretta 92X OEM)","18rd (Mec-Gar flush-fit)","20rd (Mec-Gar extended)"]),
]


def create_db():
    DB.parent.mkdir(exist_ok=True)
    con = sqlite3.connect(DB)
    con.execute("PRAGMA foreign_keys = ON")

    # Drop existing tables and recreate
    con.executescript("""
        DROP TABLE IF EXISTS buy_mags;
        DROP TABLE IF EXISTS mag_options;
        DROP TABLE IF EXISTS buy_pistols;
        DROP TABLE IF EXISTS pistols;
    """)
    con.executescript(SCHEMA.read_text())

    for p in PISTOLS:
        cur = con.execute("""
            INSERT INTO pistols
              (rank, rd, src, model, cal, purpose, price_min, price_max,
               pre_ban, rec, mag_price, brands, compat, note, link_mag)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (p["rank"], p["rd"], p["src"], p["model"], p["cal"],
              p["purpose"], p["price_min"], p["price_max"],
              1 if p["pre_ban"] else 0,
              p["rec"], p["mag_price"], p["brands"], p["compat"],
              p.get("note", ""), p.get("link_mag", "")))
        pid = cur.lastrowid

        for i, term in enumerate(p["buy_pistols"]):
            con.execute("INSERT INTO buy_pistols (pistol_id, search_term, sort_order) VALUES (?,?,?)", (pid, term, i))
        for i, display in enumerate(p["mags"]):
            con.execute("INSERT INTO mag_options (pistol_id, display, sort_order) VALUES (?,?,?)", (pid, display, i))
        for i, term in enumerate(p["buy_mags"]):
            con.execute("INSERT INTO buy_mags (pistol_id, search_term, sort_order) VALUES (?,?,?)", (pid, term, i))

    con.commit()
    con.close()
    print(f"Created {DB} with {len(PISTOLS)} pistols")


if __name__ == "__main__":
    create_db()
